name: Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: 'docs'  # Adjust this if your Jekyll source folder is different
          destination: '_site'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
